# Generated by Django 5.2.1 on 2025-05-26 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_sosdevice_latitude_alter_sosdevice_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosdevice',
            name='device_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='device',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='tracker.sosdevice'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
