# Generated by Django 5.2.1 on 2025-05-26 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_sosdevice_device_id_alter_user_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device',
        ),
        migrations.AddField(
            model_name='sosdevice',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='tracker.user'),
        ),
    ]
